### ISSUE TITLE
Autolike Okcupid does not works

### ISSUE THREAD

**Issue by ghost** [nemanjan00/OkCupid-Autolike#1]
why it is not working?

**Comment by nemanjan00** [comment]
It works now.
They moved to React.JS. Thank you. :)

**Comment by evgenie** [comment]
so what should i do?

**Comment by nemanjan00** [comment]
Install Tampermonkey and then open this link: 
https://raw.githubusercontent.com/nemanjan00/OkCupid-Autolike/master/OkCupid-Autolike.user.js

**Comment by evgenie** [comment]
thanks man

**Comment by evgenie** [comment]
do you have a solution for IE ?

**Comment by nemanjan00** [comment]
No. Sorry. I tried to uninstall it myself, but, no luck..

**Comment by evgenie** [comment]
it is weird
but in one computer in chrome it is loging to my okcupid account but
another it is not and it says:
(see attachment bellow in that email)

**Comment by nemanjan00** [comment]
My extension has nothing to do with your ability to login to you account
